name: Build & Push Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Nitro CLI Image
        run: |
          docker build \
            -t us-docker.pkg.dev/edgebit-containers/containers/nitro-cli \
            -f builder/dockerfiles/nitro-cli.dockerfile \
            .